table = {"telegram/views": {"service_id": 72, "price": 390, "name": "Телеграм просмотры"},
         "telegram/views_5": {"service_id": 71, "price": 970, "name": "Просмотры на 5 постов"},
         "telegram/views_10": {"service_id": 73, "price": 1850, "name": "Просмотры на 10 постов"},
         "telegram/views_20": {"service_id": 74, "price": 3560, "name": "Просмотры на 20 постов"},
         "telegram/views_50": {"service_id": 75, "price": 6120, "name": "Просмотры на 50 постов"},
         "telegram/views_100": {"service_id": 76, "price": 11590, "name": "Просмотры на 100 постов"},
         "telegram/followers": {"service_id": 70, "price": 8000, "name": "Подписчики Живые Русские"},
         "telegram/followers_ru": {"service_id": 157, "price": 29000, "name": "Подписчики | Русские | Качественные"},

         "instagram/followers_ru": {"service_id": 4, "price": 15000, "name": "Подписчики Русские"},
         "instagram/followers_ru_alive": {"service_id": 6, "price": 46000, "name": "Подписчики Русские - Живые"},
         "instagram/followers_bots": {"service_id": 140, "price": 3000, "name": "Подписчики Боты"},
         "instagram/followers_usa": {"service_id": 155, "price": 57000, "name": "Подписчики США"},
         "instagram/likes": {"service_id": 7, "price": 500, "name": "Лайки"},
         "instagram/likes_ru": {"service_id": 156, "price": 1400, "name": "Лайки Русские"},
         "instagram/likes_alive": {"service_id": 12, "price": 9800, "name": "Лайки Живые"},
         "instagram/views": {"service_id": 165, "price": 80, "name": "Просмотры - Видео - TV - Reels"},
         "instagram/views_stats": {"service_id": 19, "price": 1500, "name": "Просмотры - Видео + Охват и статистика"},
         "instagram/views_stats_visit": {"service_id": 152, "price": 2700, "name": "Просмотры - Видео + Охват и статистика"},
         "instagram/views_stream": {"service_id": 148, "price": 65000, "name": "Просмотры - Прямой эфир"},

         "vk/followers_offers": {"service_id": 50, "price": 21800, "name": "Подписчики - Офферные"},
         "vk/followers_top": {"service_id": 130, "price": 24000, "name": "Подписчики - Качественные"},
         "vk/followers_alive": {"service_id": 52, "price": 27000, "name": "Подписчики - Живые"},
         "vk/followers_ru": {"service_id": 131, "price": 40000, "name": "Подписчики - Русские"},
         "vk/friends": {"service_id": 133, "price": 18000, "name": "Друзья"},
         "vk/friends_alive": {"service_id": 54, "price": 25000, "name": "Друзья - Живые"},
         "vk/friends_ru": {"service_id": 132, "price": 40000, "name": "Друзья - Русские"},
         "vk/likes_fast": {"service_id": 55, "price": 24000, "name": "Лайки - Быстрые"},
         "vk/likes_group": {"service_id": 56, "price": 9000, "name": "Лайки - Группа/Паблик"},
         "vk/likes_alive": {"service_id": 57, "price": 13500, "name": "Лайки - Живые"},
         "vk/likes_alive_ru": {"service_id": 159, "price": 18000, "name": "Лайки - Живые - Россия"},
         "vk/views_group": {"service_id": 60, "price": 4000, "name": "Просмотры для группы/паблика"},
         "vk/views_profile": {"service_id": 59, "price": 5000, "name": "Просмотры для группы/профиля"},
         "vk/views_clips": {"service_id": 136, "price": 2400, "name": "Просмотры - Клипы"},
         "vk/repost_fast": {"service_id": 61, "price": 23000, "name": "Репосты - Быстрые"},
         "vk/repost_alive": {"service_id": 62, "price": 24000, "name": "Репосты - Живые"}
         }
